language: go
sudo: false
go:
  - 1.7
  - 1.8
  - 1.9
  - tip

before_script:
  - openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem -subj '/CN=localhost'

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken kLNKspQO1aS2v5rSo3idN3NSDFVwONBIt
